dataset_location: /home/mmilenkovic/images
training_images_to_use: 5000
batch_size: 64
image_size: 128 #we resize our training images to sz x sz
channels: 1
z_size: 100
lr: 0.0001
epochs: 3
num_workers: 8
clip_value: 0.01
wandb_relogin: False #if true, manually log in to wandb, and uses wandb_api_key, otherwise use the default
wandb_api_key: asdfasdfasdf