batch_size: 64
c_times: 3
channels: 1
clip_value: 0.01
dataset_location: /home/mmilenkovic/images/
epochs: 100
g_times: 1
image_size: 64
lr_critic: 0.0005
lr_generator: 0.0005
max_summary_images: 4
model_name: DC
ngf: 64
num_workers: 8
training_images_to_use: 5000
wandb_api_key: asdfasdfasdf
wandb_relogin: false
z_size: 100
